scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'reservation-postgres'
    static_configs:
      - targets: ['localhost:9187']    # 컨테이너 이름 대신 localhost 사용

  - job_name: 'reservation-nginx'
    static_configs:
      - targets: ['localhost:9113']    # 컨테이너 이름 대신 localhost 사용

  - job_name: 'reservation-cadvisor'
    static_configs:
      - targets: ['localhost:8090']    # 호스트에 매핑된 포트 사용