global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'reservation-postgres'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['reservation-postgres-exporter:9187']

  - job_name: 'reservation-nginx'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['reservation-nginx-exporter:9113']

  - job_name: 'reservation-cadvisor'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['reservation-cadvisor:8080']

  - job_name: 'reservation-node'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['reservation-node-exporter:9100']