global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'reservation-postgres'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['10.178.0.2:9187']

  - job_name: 'reservation-nginx'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['10.178.0.2:9113']

  - job_name: 'reservation-cadvisor'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['10.178.0.2:8090']