global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'reservation-postgres'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['127.0.0.1:9187']   # localhost 사용

  - job_name: 'reservation-nginx'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['127.0.0.1:9113']   # localhost 사용

  - job_name: 'reservation-cadvisor'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['127.0.0.1:8090']   # 8090으로 매핑된 포트 사용

  - job_name: 'reservation-node'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['127.0.0.1:9100']   # localhost 사용