global:
 scrape_interval: 15s
 evaluation_interval: 15s

scrape_configs:
 - job_name: 'prometheus'
   static_configs:
     - targets: ['localhost:9090']

 - job_name: 'node'
   static_configs:
     - targets: ['node-exporter:9100']

 - job_name: 'reservation-postgres'
   static_configs:
     - targets: ['reservation-postgres-exporter:9187']

 - job_name: 'reservation-nginx'
   static_configs:
     - targets: ['reservation-nginx-exporter:9113']

 - job_name: 'reservation-cadvisor'
   static_configs:
     - targets: ['reservation-cadvisor:8080']